

service: foodometer-application

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1


functions:
  foodometer:
    handler: handler.app
    events:
      - http:
          path: /foodometer
          method: POST
          cors: true 
