

service: foodometer-application

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1


functions:
  foodometer:
    handler: handler.app
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: /foodometer
          method: POST
          cors: true 
      - http:
          path: /foodometer/register
          method: POST
          cors: true     
